name: savings_fund_planner
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  custom_navigation_bar: ^0.8.2
  go_router: ^14.2.1
  image_picker: ^1.1.2
  modal_bottom_sheet: any
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  provider: ^6.1.2
  intl: ^0.19.0
  syncfusion_flutter_charts: ^20.2.39
  smooth_page_indicator: ^1.2.0+3
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  isar_generator: ^3.1.0+1
  mobx_codegen: ^2.6.1
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - assets/images/list_is_empty.png
    - assets/icon.png
    - assets/images/noPhoto.png
    - assets/images/onboarding/onboarding1.png
    - assets/images/onboarding/onboarding2.png
    - assets/images/onboarding/onboarding3.png
    - assets/images/onboarding/onboarding4.png
    - assets/images/onboarding/onboarding5.png

flutter_launcher_icons:
  android:
    adaptive_icon_background: "#0d0d0d"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000095"
  image: assets/splash.png
  android: true
  ios: true
  web: false

  android_12:
    color: "#000095"
    image: assets/splash.png
    android_gravity: fit
